### ISSUE TITLE
Stopping kopf takes too long (45+ seconds)

### ISSUE THREAD

**Issue by chungktran** [zalando-incubator/kopf#239] opened 2019-11-16 04:55 UTC
## Expected Behavior
Pressing Ctrl+c to stop kopf should stop right away or couple of seconds.

## Actual Behavior
Pressing Ctrl+c to stop kopf and it took 45+ seconds to quit. This is very tiresome during development. 

## Steps to Reproduce the Problem

  1. Run kopf with or without `--dev` flag
  1. Press Ctrl+c once or twice to stop kopf
  1. Wait long time for kopf to completely stop

**Comment by sniranjan** [comment] 2019-11-16 15:34
I am seeing the same behaviour in Mac OS

**Comment by nolar** [comment] 2019-11-17 10:49
Duplicate of #142. This should be fixed with `kopf>=0.23rc1` (try `0.23rc4`) in #227 (previously attempted in #176 and #152).

**Comment by chungktran** [comment] 2019-11-18 16:10
@nolar How do I install 0.23r4? I cloned the repo and did a `pip install ./kopf` and it still installs `0.22`. I downloaded the asset and did the same and it still installs `0.22`. I tried `python setup.py` and it threw diff error about setuptools. Thanks.

**Comment by chungktran** [comment] 2019-11-18 16:21
@nolar I get the error below using `0.23r4` when running kopf with or without `--dev- flag.
```
$ kopf run release.py                                                                                                                                                                                                     1 ?
[2019-11-18 11:15:09,115] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-18 11:15:09,142] kopf.activities.auth [INFO    ] Handler 'login_via_pykube' succeeded.
[2019-11-18 11:15:09,167] kopf.activities.auth [INFO    ] Handler 'login_via_client' succeeded.
[2019-11-18 11:15:09,168] kopf.reactor.activit [INFO    ] Initial authentication has finished.
Traceback (most recent call last):
  File "/home/ctran/.venv/release/bin/kopf", line 8, in <module>
    sys.exit(main())
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/cli.py", line 31, in wrapper
    return fn(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/cli.py", line 78, in run
    vault=__controls.vault,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 113, in run
    vault=vault,
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 153, in operator
    vault=vault,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py", line 239, in spawn_tasks
    standalone=standalone, namespace=namespace, name=peering_name,
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/engines/peering.py", line 116, in detect
    if await Peer._is_peering_exist(name=PEERING_DEFAULT_NAME, namespace=namespace):
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/engines/peering.py", line 158, in _is_peering_exist
    obj = await fetching.read_obj(resource=resource, namespace=namespace, name=name, default=None)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/clients/auth.py", line 34, in wrapper
    return await fn(*args, **kwargs, session=session)
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/kopf/clients/fetching.py", line 57, in read_obj
    url=resource.get_url(server=session.server, namespace=namespace, name=name),
  File "/home/ctran/.venv/release/lib/python3.7/site-packages/aiohttp/client.py", line 442, in _request
    raise ValueError("Cannot combine AUTHORIZATION header "
ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL
Task was destroyed but it is pending!
task: <Task pending coro=<_root_task_checker() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:418> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4895054250>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_startup_cleanup_activities() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:496> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f489503d490>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<_stop_flag_checker() running at /home/ctran/.venv/release/lib/python3.7/site-packages/kopf/reactor/running.py:447> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f489503d090>()]>>
```

**Comment by nolar** [comment] 2019-11-18 16:40
@chungktran Can you please create this as a separate issue? Please, put this stacktrace there.

And also, if possible, your `~/.kube/config` — but please **remove any passwords, tokens, secrets, hostnames** from there. I would like to understand how both username+password AND a token happen do get there at the same time. If it is not possible — it is fine.

**Comment by chungktran** [comment] 2019-11-19 03:04
@nolar filed this ticket https://github.com/zalando-incubator/kopf/issues/242

**Comment by nolar** [comment] 2019-12-07 21:25
I assume, the original issue is fixed (as it is fixed for our own operators). 

If it reappears with `kopf>=0.23.2`, please re-open this issue or open a new one.

**Closed by nolar** 2019-12-07 21:25 UTC
Labels: bug
